# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IOOI3mhE3G8MRzSdqkzEdVSYxFq_bYjY
"""

N = int(input())
x = list(map(int, input().split()))
if len(x)==N and max(x)<=(2*10e9):
  z = set(x)
  print(len(z))
else:
  print('no')

