# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IOOI3mhE3G8MRzSdqkzEdVSYxFq_bYjY
"""

x = map(int, input().split())
z = set()
for i in x:
  if i in z:
    print(i, 'yes')
  else:
    z.add(i)
    print(i, 'no')

